import type { Track, Event, Character, Location, OutlineNode } from '@/types';

/**
 * 工作区示例模板的纯数据定义。
 * 前端用做「新建工作区」向导的预览；后端通过 templateId 映射到同名种子逻辑。
 * 本地 ID 仅为可读占位符，后端写入时会重新生成 UUID 并维护关联关系。
 */

export interface SeedTemplate {
  id: string;
  nameKey: string;
  descriptionKey: string;
  icon: string;
  data: {
    tracks: Omit<Track, 'id' | 'workspaceId' | 'createdAt'>[];
    events: Omit<Event, 'id' | 'workspaceId' | 'trackId' | 'createdAt' | 'updatedAt'>[];
    characters: Omit<Character, 'id' | 'workspaceId' | 'createdAt' | 'updatedAt' | 'eventIds'>[];
    locations: Omit<Location, 'id' | 'workspaceId' | 'createdAt' | 'updatedAt'>[];
    outlineNodes: Omit<OutlineNode, 'id' | 'workspaceId' | 'eventId' | 'createdAt' | 'updatedAt'>[];
  };
}

export const WORKSPACE_TEMPLATES: SeedTemplate[] = [
  {
    id: 'fantasy-novel',
    nameKey: 'workspace.form.templateFantasy',
    descriptionKey: 'workspace.form.templateFantasyDesc',
    icon: 'sword',
    data: {
      tracks: [
        { name: '主线', color: '#F4B6C2', sortOrder: 0, isVisible: true },
        { name: '魔法线', color: '#B6D4F4', sortOrder: 1, isVisible: true },
        { name: '阵营线', color: '#B6F4C8', sortOrder: 2, isVisible: true },
        { name: '成长线', color: '#F4E4B6', sortOrder: 3, isVisible: true },
      ],
      characters: [
        {
          name: '艾莉恩',
          aliases: ['月裔'],
          avatar: null,
          description: '银月城最年轻的法师学徒，体内沉睡着上古月神血脉。',
          appearance: '银白色长发，眼眸在施法时会泛出淡蓝微光。',
          backstory: '幼时被贤者奥伦从废墟中救出，在法师塔长大。',
          goals: '掌控自身血脉，阻止莫拉丝的复活仪式。',
          conflicts: '力量越强大，越容易被月神意识侵蚀。',
          arc: '从自卑的学徒成长为能独当一面的守护者。',
          tags: ['主角', '法师', '月神血脉'],
          color: '#B6D4F4',
        },
        {
          name: '凯尔',
          aliases: ['铁壁'],
          avatar: null,
          description: '前王国骑士，性格沉稳，现为艾莉恩的护卫。',
          appearance: '身披陈旧板甲，左脸有一道旧伤疤。',
          backstory: '因拒绝处决平民而被剥夺骑士头衔，流亡多年。',
          goals: '赎清过往罪孽，保护艾莉恩完成使命。',
          conflicts: '对王国的忠诚与对正义的坚持互相撕扯。',
          arc: '从自我放逐到重新拾起守护的信念。',
          tags: ['护卫', '骑士'],
          color: '#F4CBB6',
        },
        {
          name: '莫拉丝',
          aliases: ['黑鸦女巫'],
          avatar: null,
          description: '千年前被封印的巫师，企图借助月食重返世间。',
          appearance: '身披漆黑羽氅，双眼如燃尽的余烬。',
          backstory: '曾是月神祭司，因触碰禁忌知识而堕落。',
          goals: '吞噬月神血脉，成为新神。',
          conflicts: '被封印的本体无法离开遗迹核心。',
          arc: '从陨落祭司到终极威胁。',
          tags: ['反派', '巫师'],
          color: '#D8B6F4',
        },
        {
          name: '老贤者奥伦',
          aliases: ['奥伦'],
          avatar: null,
          description: '艾莉恩的养父与导师，掌握古老封印术。',
          appearance: '白须及胸，手持橡木法杖。',
          backstory: '最后一代星象师，毕生致力于看守莫拉丝的封印。',
          goals: '引导艾莉恩学会控制血脉。',
          conflicts: '年迈的身躯已无法承受高强度施法。',
          arc: '从守护者变为牺牲者，为后辈铺平道路。',
          tags: ['导师', '法师'],
          color: '#F4E4B6',
        },
      ],
      locations: [
        {
          name: '银月城',
          description: '王国边境的魔法都市，以高耸的月之神殿闻名。',
          posX: 120,
          posY: 100,
          color: '#B6D4F4',
          icon: '🏰',
          linkedEventId: null,
          characterIds: [],
        },
        {
          name: '黑森林',
          description: '被古老诅咒笼罩的森林，通往遗迹的必经之路。',
          posX: 280,
          posY: 220,
          color: '#B6F4C8',
          icon: '🌲',
          linkedEventId: null,
          characterIds: [],
        },
        {
          name: '古代遗迹',
          description: '月神时代的地下祭坛，莫拉丝被封印于此。',
          posX: 420,
          posY: 160,
          color: '#D8B6F4',
          icon: '🏛️',
          linkedEventId: null,
          characterIds: [],
        },
      ],
      events: [
        {
          title: '银月城遇袭',
          description: '黑鸦军团夜袭城市，艾莉恩的血脉首次失控爆发。',
          dateType: 'relative',
          dateValue: '第 1 天',
          sortOrder: 0,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
        {
          title: '接受使命',
          description: '奥伦告知艾莉恩血脉真相，凯尔正式加入队伍。',
          dateType: 'relative',
          dateValue: '第 3 天',
          sortOrder: 1,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
        {
          title: '黑森林试炼',
          description: '队伍穿越黑森林，艾莉恩学会初步控制月神之力。',
          dateType: 'relative',
          dateValue: '第 7 天',
          sortOrder: 2,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
        {
          title: '遗迹觉醒',
          description: '莫拉丝借助月食削弱封印，遗迹中的古代机关被激活。',
          dateType: 'relative',
          dateValue: '第 14 天',
          sortOrder: 3,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
        {
          title: '最终对决',
          description: '艾莉恩在月之神殿顶端与莫拉丝展开决战。',
          dateType: 'relative',
          dateValue: '第 15 天',
          sortOrder: 4,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
      ],
      outlineNodes: [
        { type: 'volume', title: '第一卷：月之觉醒', content: '艾莉恩发现自身血脉，踏上阻止莫拉丝的旅程。', parentId: null, sortOrder: 0, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第一章：银月城的夜晚', content: '黑鸦军团夜袭，血脉初次觉醒。', parentId: 'volume-1', sortOrder: 0, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第二章：贤者的真相', content: '奥伦揭示身世，凯尔加入队伍。', parentId: 'volume-1', sortOrder: 1, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第三章：黑森林的低语', content: '穿越诅咒森林，学习控制力量。', parentId: 'volume-1', sortOrder: 2, status: 'draft', coverImage: null },
        { type: 'volume', title: '第二卷：遗迹之战', content: '前往古代遗迹，直面莫拉丝。', parentId: null, sortOrder: 1, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第四章：封印松动', content: '月食之夜，遗迹机关启动。', parentId: 'volume-2', sortOrder: 0, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第五章：神殿之巅', content: '最终对决与自我牺牲。', parentId: 'volume-2', sortOrder: 1, status: 'draft', coverImage: null },
      ],
    },
  },
  {
    id: 'urban-romance',
    nameKey: 'workspace.form.templateUrbanRomance',
    descriptionKey: 'workspace.form.templateUrbanRomanceDesc',
    icon: 'heart',
    data: {
      tracks: [
        { name: '感情线', color: '#F4B6C2', sortOrder: 0, isVisible: true },
        { name: '事业线', color: '#B6D4F4', sortOrder: 1, isVisible: true },
        { name: '家庭线', color: '#F4E4B6', sortOrder: 2, isVisible: true },
      ],
      characters: [
        {
          name: '林夏',
          aliases: ['夏夏'],
          avatar: null,
          description: '独立室内设计师，表面理性，内心渴望被理解。',
          appearance: '利落短发，常穿oversized西装外套。',
          backstory: '父母离异后随母亲生活，靠奖学金完成设计学业。',
          goals: '举办个人设计展，证明自己。',
          conflicts: '母亲的催婚与自己对感情的恐惧。',
          arc: '从封闭内心到学会信任与依赖。',
          tags: ['主角', '设计师'],
          color: '#F4B6C2',
        },
        {
          name: '顾沉',
          aliases: ['顾老板'],
          avatar: null,
          description: '梧桐咖啡馆老板，温柔寡言，曾是建筑设计师。',
          appearance: '眉眼温和，手指因常年泡咖啡而带着薄茧。',
          backstory: '因一场设计事故离开行业，继承祖母的咖啡馆。',
          goals: '让咖啡馆成为城市中让人安心的角落。',
          conflicts: '过去的失败阴影让他不敢重新开始设计。',
          arc: '在林夏的鼓励下重拾设计图纸。',
          tags: ['男主', '咖啡师'],
          color: '#B6D4F4',
        },
        {
          name: '苏晴',
          aliases: ['晴晴'],
          avatar: null,
          description: '林夏的闺蜜兼经纪人，直率热情。',
          appearance: '一头卷发，永远带着夸张的耳环。',
          backstory: '与林夏大学相识，一同在设计圈摸爬滚打。',
          goals: '把林夏推上更大的舞台。',
          conflicts: '过于保护林夏，有时反而造成压力。',
          arc: '学会尊重好友的节奏。',
          tags: ['闺蜜', '经纪人'],
          color: '#F4E4B6',
        },
        {
          name: '林母',
          aliases: [],
          avatar: null,
          description: '林夏的母亲，传统而关心女儿。',
          appearance: '喜欢穿旗袍，说话直接。',
          backstory: '独自抚养女儿长大，对婚姻有自己的执念。',
          goals: '希望女儿早日成家。',
          conflicts: '与林夏在生活方式上理念不合。',
          arc: '逐渐理解女儿对事业的追求。',
          tags: ['家人'],
          color: '#B6F4C8',
        },
      ],
      locations: [
        {
          name: '梧桐咖啡馆',
          description: '街角的复古咖啡馆，顾沉经营多年。',
          posX: 140,
          posY: 120,
          color: '#F4B6C2',
          icon: '☕',
          linkedEventId: null,
          characterIds: [],
        },
        {
          name: '旧公寓',
          description: '林夏租住的老公寓，堆满面料样本与设计稿。',
          posX: 300,
          posY: 200,
          color: '#F4E4B6',
          icon: '🏠',
          linkedEventId: null,
          characterIds: [],
        },
        {
          name: '设计工作室',
          description: '林夏与苏晴共用的小型工作室。',
          posX: 460,
          posY: 120,
          color: '#B6D4F4',
          icon: '📐',
          linkedEventId: null,
          characterIds: [],
        },
      ],
      events: [
        {
          title: '雨夜重逢',
          description: '林夏在梧桐咖啡馆躲雨，与多年未见的顾沉重逢。',
          dateType: 'relative',
          dateValue: '相识第 1 天',
          sortOrder: 0,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
        {
          title: '咖啡馆常客',
          description: '林夏习惯在咖啡馆画图，两人逐渐熟络。',
          dateType: 'relative',
          dateValue: '相识第 7 天',
          sortOrder: 1,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
        {
          title: '误会与争吵',
          description: '设计展机会引发林夏与顾沉关于「过去」的争执。',
          dateType: 'relative',
          dateValue: '相识第 21 天',
          sortOrder: 2,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
        {
          title: '设计展重逢',
          description: '林夏的设计展上，顾沉以设计师身份重新出现。',
          dateType: 'relative',
          dateValue: '相识第 45 天',
          sortOrder: 3,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
        {
          title: '告白',
          description: '雨夜咖啡馆打烊后，顾沉终于说出心意。',
          dateType: 'relative',
          dateValue: '相识第 46 天',
          sortOrder: 4,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
      ],
      outlineNodes: [
        { type: 'volume', title: '第一卷：相遇', content: '林夏与顾沉在梧桐咖啡馆重逢，感情慢慢升温。', parentId: null, sortOrder: 0, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第一章：雨夜的咖啡香', content: '重逢与初识，顾沉递给林夏一条毛巾。', parentId: 'volume-1', sortOrder: 0, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第二章：画纸与拿铁', content: '林夏成为常客，两人分享各自的设计理想。', parentId: 'volume-1', sortOrder: 1, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第三章：旧伤痕', content: '误会让关系降至冰点。', parentId: 'volume-1', sortOrder: 2, status: 'draft', coverImage: null },
        { type: 'volume', title: '第二卷：告白', content: '设计展成为两人重新靠近的契机。', parentId: null, sortOrder: 1, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第四章：重新出发', content: '顾沉回归设计圈，林夏为他加油。', parentId: 'volume-2', sortOrder: 0, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第五章：雨停之后', content: '告白与新的开始。', parentId: 'volume-2', sortOrder: 1, status: 'draft', coverImage: null },
      ],
    },
  },
  {
    id: 'ttrpg-campaign',
    nameKey: 'workspace.form.templateTtrpg',
    descriptionKey: 'workspace.form.templateTtrpgDesc',
    icon: 'dice',
    data: {
      tracks: [
        { name: '主线任务', color: '#F4B6C2', sortOrder: 0, isVisible: true },
        { name: '支线委托', color: '#B6D4F4', sortOrder: 1, isVisible: true },
        { name: '世界事件', color: '#B6F4C8', sortOrder: 2, isVisible: true },
        { name: '角色个人', color: '#F4E4B6', sortOrder: 3, isVisible: true },
      ],
      characters: [
        {
          name: 'DM 叙事者',
          aliases: ['守秘人'],
          avatar: null,
          description: '桌面战役的地下城主，负责推动剧情与扮演 NPC。',
          appearance: '由 DM 自行设定形象。',
          backstory: '世界的观察者。',
          goals: '为玩家带来一场难忘的冒险。',
          conflicts: '平衡挑战与乐趣。',
          arc: '引导玩家书写自己的传奇。',
          tags: ['DM', 'NPC'],
          color: '#D8B6F4',
        },
        {
          name: '艾尔文',
          aliases: ['精灵游侠'],
          avatar: null,
          description: '来自迷雾山脉的精灵游侠，擅长追踪与远程攻击。',
          appearance: '尖耳银发，背着一把长弓。',
          backstory: '故乡被兽人部落焚毁，誓要保护最后的森林。',
          goals: '找到失落的精灵圣物。',
          conflicts: '对人类的偏见让他难以信任队友。',
          arc: '从孤狼成长为团队的一员。',
          tags: ['PC', '游侠'],
          color: '#B6F4C8',
        },
        {
          name: '布鲁克',
          aliases: ['矮人战士'],
          avatar: null,
          description: '豪爽的矮人战士，队伍中坚。',
          appearance: '浓密红胡，身穿重甲，手持战斧。',
          backstory: '为洗刷家族污名而外出冒险。',
          goals: '赚够金币重建家族矿坑。',
          conflicts: '贪婪与荣誉之间的拉扯。',
          arc: '学会为同伴而非金钱战斗。',
          tags: ['PC', '战士'],
          color: '#F4CBB6',
        },
        {
          name: '莉莉',
          aliases: ['人类法师'],
          avatar: null,
          description: '渴望知识的人类法师，偶尔冲动。',
          appearance: '随身携带一本厚重的法术书。',
          backstory: '出身学徒，因偷阅禁书被学院警告。',
          goals: '解开古代魔法的秘密。',
          conflicts: '对力量的渴望可能带来危险。',
          arc: '从冒进学徒变成谨慎的施法者。',
          tags: ['PC', '法师'],
          color: '#B6D4F4',
        },
      ],
      locations: [
        {
          name: '深水镇',
          description: '冒险者聚集的边境小镇，队伍出发地。',
          posX: 120,
          posY: 140,
          color: '#F4CBB6',
          icon: '🏘️',
          linkedEventId: null,
          characterIds: [],
        },
        {
          name: '迷雾山脉',
          description: '精灵遗迹与兽人部落并存的危险山脉。',
          posX: 300,
          posY: 80,
          color: '#B6F4C8',
          icon: '⛰️',
          linkedEventId: null,
          characterIds: [],
        },
        {
          name: '地下城入口',
          description: '通往古代矮人王国的石门，传说藏有圣物。',
          posX: 440,
          posY: 200,
          color: '#D8B6F4',
          icon: '🕳️',
          linkedEventId: null,
          characterIds: [],
        },
      ],
      events: [
        {
          title: '酒馆集结',
          description: '四位冒险者在深水镇酒馆相遇，接受镇长委托。',
          dateType: 'relative',
          dateValue: '战役第 1 天',
          sortOrder: 0,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
        {
          title: '接受委托',
          description: '镇长委托队伍调查地下城异动。',
          dateType: 'relative',
          dateValue: '战役第 1 天',
          sortOrder: 1,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
        {
          title: '遭遇伏击',
          description: '前往地下城途中，队伍在迷雾山脉遭到兽人伏击。',
          dateType: 'relative',
          dateValue: '战役第 3 天',
          sortOrder: 2,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
        {
          title: '地下城探索',
          description: '队伍进入古代矮人遗迹，解开机关与谜题。',
          dateType: 'relative',
          dateValue: '战役第 5 天',
          sortOrder: 3,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
        {
          title: 'Boss 战',
          description: '遗迹深处，被诅咒的矮人国王苏醒。',
          dateType: 'relative',
          dateValue: '战役第 6 天',
          sortOrder: 4,
          status: 'draft',
          color: null,
          locationId: null,
          imageUrls: [],
          characterIds: [],
          connectedEventIds: [],
        },
      ],
      outlineNodes: [
        { type: 'volume', title: '第一幕：集结', content: '冒险者相遇并接受委托。', parentId: null, sortOrder: 0, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第一章：深水镇酒馆', content: 'PC 初次见面，DM 介绍背景。', parentId: 'volume-1', sortOrder: 0, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第二章：镇长的委托', content: '队伍获得地下城情报与初始装备。', parentId: 'volume-1', sortOrder: 1, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第三章：迷雾山脉', content: '第一次战斗遭遇，建立团队配合。', parentId: 'volume-1', sortOrder: 2, status: 'draft', coverImage: null },
        { type: 'volume', title: '第二幕：地下城', content: '探索遗迹，面对最终 Boss。', parentId: null, sortOrder: 1, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第四章：遗迹机关', content: '解谜与陷阱，发现圣物线索。', parentId: 'volume-2', sortOrder: 0, status: 'draft', coverImage: null },
        { type: 'chapter', title: '第五章：诅咒国王', content: '最终战斗与战后抉择。', parentId: 'volume-2', sortOrder: 1, status: 'draft', coverImage: null },
      ],
    },
  },
];
