import { describe, expect, it } from 'vitest';

import {
  enhanceRenpyExport,
  parseRenpyVariables,
  sanitizeRenpyIdentifier,
} from './renpyEnhance';

const HEADER = "# Ren'Py script generated by Plotline";

function makeScript(): string {
  return [
    HEADER,
    '',
    'define e = Character("Eileen")',
    '',
    '# Scene: 开场',
    'label start:',
    '    scene bg school',
    '    e "你好"',
    '',
    '# Scene: 校门',
    'label gate:',
    '    "旁白文本"',
    '',
  ].join('\n');
}

describe('enhanceRenpyExport transitions', () => {
  it('should insert with dissolve after the first scene bg of a label block', () => {
    const out = enhanceRenpyExport(makeScript(), { transition: 'dissolve' });
    expect(out).toContain('    scene bg school\n    with dissolve\n    e "你好"');
  });

  it('should insert with fade when transition is fade', () => {
    const out = enhanceRenpyExport(makeScript(), { transition: 'fade' });
    expect(out).toContain('    scene bg school\n    with fade\n    e "你好"');
    expect(out).not.toContain('    with dissolve');
  });

  it('should not insert any with line when transition is none', () => {
    const out = enhanceRenpyExport(makeScript(), { transition: 'none' });
    expect(out).toBe(makeScript());
  });

  it('should not insert with for a scene without bg', () => {
    const script = [
      HEADER,
      '',
      'label empty:',
      '    "没有背景"',
      '',
    ].join('\n');
    const out = enhanceRenpyExport(script, { transition: 'dissolve' });
    expect(out).not.toContain('with dissolve');
    expect(out).toBe(script);
  });

  it('should not insert with when the scene already contains a with statement', () => {
    const script = [
      HEADER,
      '',
      'label start:',
      '    scene bg school',
      '    with fade',
      '    e "你好"',
      '',
    ].join('\n');
    const out = enhanceRenpyExport(script, { transition: 'dissolve' });
    expect(out).toBe(script);
  });
});

describe('enhanceRenpyExport variables', () => {
  it('should insert default variable lines before the first define/label', () => {
    const out = enhanceRenpyExport(makeScript(), {
      variables: [
        { name: 'day', value: '1' },
        { name: 'gold', value: '10' },
      ],
    });
    expect(out).toContain('default day = 1\ndefault gold = 10');
    expect(out.indexOf('default day = 1')).toBeLessThan(out.indexOf('define e'));
  });

  it('should skip invalid variable names', () => {
    const out = enhanceRenpyExport(makeScript(), {
      variables: [
        { name: '1bad', value: '1' },
        { name: 'bad-name', value: '2' },
        { name: 'ok', value: '3' },
      ],
    });
    expect(out).toContain('default ok = 3');
    expect(out).not.toContain('default 1bad');
    expect(out).not.toContain('default bad-name');
  });

  it('should replace newlines in variable values with spaces', () => {
    const out = enhanceRenpyExport(makeScript(), {
      variables: [{ name: 'note', value: 'line1\nline2' }],
    });
    expect(out).toContain('default note = line1 line2');
  });

  it('should not insert a variable block for an empty variable list', () => {
    const out = enhanceRenpyExport(makeScript(), { variables: [] });
    expect(out).toBe(makeScript());
  });

  it('should not duplicate existing default lines', () => {
    const script = [
      HEADER,
      '',
      'default day = 1',
      '',
      'label start:',
      '    scene bg school',
      '    e "你好"',
      '',
    ].join('\n');
    const out = enhanceRenpyExport(script, {
      variables: [{ name: 'day', value: '1' }],
    });
    expect(out).toBe(script);
  });
});

describe('enhanceRenpyExport idempotency', () => {
  it('should be idempotent with the same options', () => {
    const options = {
      transition: 'dissolve' as const,
      variables: [
        { name: 'day', value: '1' },
        { name: 'gold', value: '10' },
      ],
    };
    const once = enhanceRenpyExport(makeScript(), options);
    const twice = enhanceRenpyExport(once, options);
    expect(twice).toBe(once);
  });

  it('should be idempotent when only variables are applied', () => {
    const options = {
      variables: [{ name: 'day', value: '1' }],
    };
    const once = enhanceRenpyExport(makeScript(), options);
    const twice = enhanceRenpyExport(once, options);
    expect(twice).toBe(once);
  });
});

describe('parseRenpyVariables', () => {
  it('should parse name = value and name=value lines', () => {
    const text = [
      '# 注释',
      'day = 1',
      'gold=10',
      '',
      'name = Alice',
    ].join('\n');
    expect(parseRenpyVariables(text)).toEqual([
      { name: 'day', value: '1' },
      { name: 'gold', value: '10' },
      { name: 'name', value: 'Alice' },
    ]);
  });

  it('should skip invalid names and comment lines', () => {
    const text = [
      '# day = 99',
      '1bad = 1',
      'bad-name = 2',
      'ok = 3',
      'no_equals',
    ].join('\n');
    expect(parseRenpyVariables(text)).toEqual([{ name: 'ok', value: '3' }]);
  });

  it('should return an empty array for empty input', () => {
    expect(parseRenpyVariables('')).toEqual([]);
  });
});

describe('sanitizeRenpyIdentifier', () => {
  it('should accept valid RenPy identifiers and trim whitespace', () => {
    expect(sanitizeRenpyIdentifier('  day_1  ')).toBe('day_1');
    expect(sanitizeRenpyIdentifier('_private')).toBe('_private');
  });

  it('should reject invalid RenPy identifiers', () => {
    expect(sanitizeRenpyIdentifier('1day')).toBeNull();
    expect(sanitizeRenpyIdentifier('day-1')).toBeNull();
    expect(sanitizeRenpyIdentifier('')).toBeNull();
  });
});
