/**
 * Ren'Py 导出增强：纯前端后处理。
 *
 * 职责：
 * - 给每个含背景的场景自动补 `with` 转场。
 * - 在文件头之后插入 `default <name> = <value>` 变量块。
 * - 从多行文本解析 `name = value` 变量定义。
 */

export type RenpyTransition = 'none' | 'dissolve' | 'fade';

export interface RenpyVariable {
  name: string;
  value: string;
}

export interface RenpyEnhanceOptions {
  transition?: RenpyTransition;
  variables?: RenpyVariable[];
}

const RENPY_HEADER = "# Ren'Py script generated by Plotline";
const RENPY_IDENTIFIER_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;
const LABEL_LINE_RE = /^label\s+\S+\s*:/;
const SCENE_BG_LINE_RE = /^scene\s+bg\s+\S+/;
const WITH_LINE_RE = /^with\s+/;
const DEFAULT_LINE_RE = /^default\s+([A-Za-z_][A-Za-z0-9_]*)\s*=/;

/**
 * 校验 Ren'Py 标识符。
 *
 * 合法标识符必须以字母或下划线开头，后续只能是字母、数字或下划线。
 * 返回去除首尾空白后的标识符；非法时返回 `null`。
 */
export function sanitizeRenpyIdentifier(name: string): string | null {
  const trimmed = name.trim();
  if (!RENPY_IDENTIFIER_RE.test(trimmed)) {
    return null;
  }
  return trimmed;
}

/**
 * 按行解析 `name = value`（也支持 `name=value`）。
 *
 * 忽略空行与以 `#` 开头的注释行；name 非法的行会被跳过。
 * 返回值中的 value 已去除首尾空白。
 */
export function parseRenpyVariables(text: string): RenpyVariable[] {
  const variables: RenpyVariable[] = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }
    const eqIndex = line.indexOf('=');
    if (eqIndex < 0) {
      continue;
    }
    const name = line.slice(0, eqIndex).trim();
    if (!RENPY_IDENTIFIER_RE.test(name)) {
      continue;
    }
    const value = line.slice(eqIndex + 1).trim();
    variables.push({ name, value });
  }
  return variables;
}

/**
 * 对 Rust 导出的原始 Ren'Py 脚本做纯文本增强。
 *
 * 规则：
 * - 转场：在每个 `label <label>:` 场景块中，若该场景有 `scene bg ...` 且尚无 `with` 语句，
 *   则在第一次出现 `scene bg ...` 的行之后插入 `    with dissolve`（或 `fade`）。
 *   `none` 不插入；没有背景的场景不插入。
 * - 变量：在 `# Ren'Py script generated by Plotline` 文件头注释之后、第一个
 *   `define`/`label` 之前插入 `default <name> = <value>` 块。非法变量名跳过；
 *   value 中的换行会被替换为空格；空列表不插入。
 * - 幂等：重复调用（相同选项）不会重复插入 `with` 或变量块。
 */
export function enhanceRenpyExport(
  script: string,
  options: RenpyEnhanceOptions = {},
): string {
  const transition = options.transition ?? 'none';
  const lines = script.split(/\r?\n/);

  // ---- 转场 ----
  if (transition !== 'none') {
    const labelIndices: number[] = [];
    for (let i = 0; i < lines.length; i += 1) {
      if (LABEL_LINE_RE.test(lines[i]!.trim())) {
        labelIndices.push(i);
      }
    }

    const insertions: Array<{ index: number; line: string }> = [];
    for (let b = 0; b < labelIndices.length; b += 1) {
      const blockStart = labelIndices[b]!;
      const blockEnd = b + 1 < labelIndices.length ? labelIndices[b + 1]! : lines.length;
      const sceneBgIndex = findFirstSceneBgIndex(lines, blockStart + 1, blockEnd);
      if (sceneBgIndex < 0) {
        continue;
      }
      const hasWith = lines
        .slice(blockStart + 1, blockEnd)
        .some((line) => WITH_LINE_RE.test(line.trim()));
      if (hasWith) {
        continue;
      }
      insertions.push({ index: sceneBgIndex + 1, line: `    with ${transition}` });
    }

    // 从后往前插入，避免索引漂移。
    insertions.sort((a, b) => b.index - a.index);
    for (const insertion of insertions) {
      lines.splice(insertion.index, 0, insertion.line);
    }
  }

  // ---- 变量 ----
  const variables = options.variables ?? [];
  const existingDefaults = new Set<string>();
  for (const line of lines) {
    const match = DEFAULT_LINE_RE.exec(line.trim());
    if (match?.[1]) {
      existingDefaults.add(match[1]);
    }
  }

  const plannedNames = new Set<string>();
  const variableLines: string[] = [];
  for (const variable of variables) {
    const name = sanitizeRenpyIdentifier(variable.name);
    if (!name || existingDefaults.has(name) || plannedNames.has(name)) {
      continue;
    }
    const value = variable.value.replace(/\r?\n/g, ' ');
    variableLines.push(`default ${name} = ${value}`);
    plannedNames.add(name);
  }

  if (variableLines.length > 0) {
    const headerIndex = lines.findIndex((line) => line.trim() === RENPY_HEADER);
    let insertIndex = 0;
    if (headerIndex >= 0) {
      insertIndex = lines.length;
      for (let i = headerIndex + 1; i < lines.length; i += 1) {
        if (lines[i]!.trim() !== '') {
          insertIndex = i;
          break;
        }
      }
    }
    lines.splice(insertIndex, 0, ...variableLines);
  }

  return lines.join('\n');
}

function findFirstSceneBgIndex(lines: string[], start: number, end: number): number {
  for (let i = start; i < end; i += 1) {
    if (SCENE_BG_LINE_RE.test(lines[i]!.trim())) {
      return i;
    }
  }
  return -1;
}
